### ISSUE TITLE
Dist size is HUGE — 425kb

### ISSUE THREAD

**Issue by ikido** [wearevolt/mobx-model#10]

**Comment by jgamedev** [comment]
0.o   !?!

**Comment by ikido** [comment]
You can help by reducing it or providing some advice how to do that =)

**Comment by Staltec** [comment]
> webpack --json | webpack-bundle-size-analyzer

**bluebird: 169.27 KB (35.0%)**
**lodash: 105.85 KB (21.9%)**
**mobx: 93.57 KB (19.3%)**
inflection: 30.07 KB (6.22%)
superagent: 29.14 KB (6.02%)
qs: 14.32 KB (2.96%)
process: 5.17 KB (1.07%)
component-emitter: 3.11 KB (0.642%)
timers-browserify: 2.06 KB (0.425%)
webpack: 241 B (0.0487%)
<self>: 30.92 KB (6.39%)
