### ISSUE TITLE
invalidate cache when superagent cache is passed.

### ISSUE THREAD

**Issue by vijayst** [wearevolt/mobx-model#22]
0.27 of mobx-model allows superagent to be passed. In this way, superagent-cache can be passed and response is getting cached.

There is an option which can be passed with the request to invalidate the cache. The option is forceUpdate and it instructs the cache to make the api call anyway. The usage of this option is shown below.

```
return API.request({
      forceUpdate: true,
      endpoint: `${ENDPOINT}/${this.id}`,
      onSuccess: (response) => {
        this.set({ modelJson: response.body });
      }
    });
```

**Comment by vijayst** [comment]
@ikido I can create a PR for this and the fix for the bug in 0.27 release, if it is ok with you.

**Comment by ikido** [comment]
Hi Vijay, I don't think it's a good idea to do that since it's not unversal for all request and we can't add options for every superagent variation out there. You can pass instance of superagent-cache with every request, isn't that enough for this case?

**Comment by vijayst** [comment]
@ikido I appreciate your views. I passed superagent-cache in the config. For a specific request, I passed in superagent (non-patched), but I still receive cached results. Not sure, why. I will close the issue.
