### ISSUE TITLE
After creating a Model overwritten a simple array to an array of objects

### ISSUE THREAD

**Issue by VadSiam** [wearevolt/mobx-model#28]
After creating a Model overwritten a simple array to an array of objects, this is answer from the server : 
![first](https://cloud.githubusercontent.com/assets/13175606/21357894/8c2dae2a-c709-11e6-8ab2-5575046c10bd.jpg)

and what we have after in Model :
![second](https://cloud.githubusercontent.com/assets/13175606/21358520/8a7ec760-c70b-11e6-9f07-45d5fb99ce04.jpg)

How can I get a simple array in the Model?

**Comment by Staltec** [comment]
That is not bug of `mobx-model`. Bug in `mobx-model-json-api` wrapper library. Close this issue here.

**Comment by VadSiam** [comment]
@Staltec ok, thanks
