### ISSUE TITLE
Add default RESTful actions to BaseModel

### ISSUE THREAD

**Issue by ikido** [wearevolt/mobx-model#6]
There are common Restful actions that we use across the projects — create, update, destroy, load, loadAll. They can be added to BaseModel to reduce boilerplate code

**Comment by Staltec** [comment]
@ikido Have ideas about actions names? How about variants:

- BaseModel.create()
- BaseModel.fetch(id?) (for list without id and single model if id set)
- model.sync()
- model.update()
- model.delete()

**Comment by Staltec** [comment]
#30 Added following Restful actions:
- BaseModel.create()
- BaseModel.load()
- model.update()
- model.delete()
